### ISSUE TITLE
chaincode upgrade fails: fabric-ccenv:latest is deprecated by hlf community

### ISSUE THREAD

**Issue by LudoNieuw** [hyfen-nl/PIVT#84] opened 2020-09-11 11:11 UTC
Hi there, 

My most recent chaincode upgrade is failing, due to  `manifest for hyperledger/fabric-ccenv:latest not found: manifest unknown: manifest unknown`

I found here (https://docs.microsoft.com/en-us/answers/questions/84420/aks-hyperledger-fabric-hyperledgerfabric-ccenvlate.html) that /fabric-ccenv:**latest** tag has been deprecated by Hypereldger Fabric Community. 
And I also found their own channel:
https://lists.hyperledger.org/g/fabric/message/8703

Does anyone know an elegant way to fix this? I'm not entirely sure where this is set. the only mention of `fabric-ccenv` is in the repo at `fabric-kube/docs/hl_config_sample/core.yaml`. Our own project is derived from this, but does not feature this fabric-ccenv at all (when I search in my repo for that term)

The suggestions at https://github.com/Azure/Hyperledger-Fabric-on-Azure-Kubernetes-Service/issues/11 Do not work for this project. 

Chaincode log:
```
$ argo logs hlf-chaincodes-wfjls-2092447895 -n hlf
Chaincode participant version 22334 is not instantiated on channel pggmremote 
-- result is: 99
-- Chaincode participant version 22334 is not instantiated on channel pggmremote, will check another version..
Chaincode participant is instantiated on channel pggmremote 
-- Chaincode participant with another version is already instantiated on channel pggmremote, will perform an upgrade chaincode transaction..
2020-09-11 10:44:39.216 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 001 Using default escc
2020-09-11 10:44:39.216 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 002 Using default vscc
Error: could not assemble transaction, err proposal response was not successful, error code 500, msg error starting container: error starting container: Failed to generate platform-specific docker build: Failed to pull hyperledger/fabric-ccenv:latest: API error (404): manifest for hyperledger/fabric-ccenv:latest not found: manifest unknown: manifest unknown
```

**Comment by raftAtGit** [comment] 2020-09-11 11:18
duplicate of https://github.com/hyfen-nl/PIVT/issues/71.
you need the commit mentioned in that issue.

@LudoNieuw your local repo and this one diverging, please consider using this repo directly

**Comment by LudoNieuw** [comment] 2020-09-11 11:27
> @LudoNieuw your local repo and this one diverging, please consider using this repo directly
I'll take that to heart ❤️ 

Thanks!

**Closed** 2020-09-11 11:27 UTC
Labels: bug
